### ISSUE TITLE
Test results, the acceptance rate is always 1

### ISSUE THREAD

**Issue by lpj12121** [GeminiLight/hrl-acra#5]
![屏幕截图 2024-06-03 112232](https://github.com/GeminiLight/hrl-acra/assets/147413930/ad2dd4b2-b7cb-4dbd-9da5-45782bede298)

After I trained the model and ran several rounds of tests, I found that the acceptance rate was always 1. The acceptance rate during the validation process during training was about 0.9, which was quite different from the test results. I did not modify the core code, but I could not get results close to those in the paper. Why is this?

**Comment by lpj12121** [comment]
When I change the parameters of the virtual network, sometimes it will become 0.999. This acceptance rate is too high and it doesn't seem normal.
<img width="360" alt="image" src="https://github.com/GeminiLight/hrl-acra/assets/147413930/28d87607-99d6-4cbc-a3ad-4355feac05d5">

**Comment by GeminiLight** [comment]
Hi, could you provide me with more details so I can better understand the problems?

1. Which algorithm do you currently run?
2. How do you set the `p_net_setting.yaml` and `v_sim_setting.yaml`?
3. Could you select other baseline algorithms and report their results?

**Comment by lpj12121** [comment]
> Hi, could you provide me with more details so I can better understand the problems?
> 
> 1. Which algorithm do you currently run?
> 2. How do you set the `p_net_setting.yaml` and `v_sim_setting.yaml`?
> 3. Could you select other baseline algorithms and report their results?

1.I am verifying HRL-ACRA, and I have trained the upper and lower agents. 

2.The p_net_setting.yaml is the default value, which I did not change. The v_sim_setting.yaml is based on the comparative experiments in the paper. I am very curious why the acceptance rate is always 1 or 0.999 during the verification process. During training, there is a verification every ten rounds, and the acceptance rate finally converges to about 0.89. 

3.I have trained the A3C-GCN model before, and this is more normal and closer to the data in the paper.


This problem seems to have been mentioned in issue 1, and it looks similar to mine

**Comment by neflibata688** [comment]
Traceback (most recent call last):
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\main.py", line 32, in <module>
    run(config)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\main.py", line 17, in run
    Env, Solver = load_simulator(config.solver_name)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\base\loader.py", line 26, in load_simulator
    from solver.learning.hrl_ra import HrlRaSolver
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\hrl_ra\__init__.py", line 1, in <module>
    from .hrl_ra_solver import HrlRaSolver
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\hrl_ra\hrl_ra_solver.py", line 8, in <module>
    from .sub_env import SubEnv
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\hrl_ra\sub_env.py", line 4, in <module>
    from ..sub_rl_environment import JointPRStepSubRLEnv, PlaceStepSubRLEnv
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\sub_rl_environment.py", line 6, in <module>
    from .rl_environment import VNERLEnv
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\rl_environment.py", line 7, in <module>
    from ...base import Environment
ImportError: attempted relative import beyond top-level package
why have this question

**Comment by neflibata688** [comment]
*** Generate virtual networks with seed None
Traceback (most recent call last):
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\main.py", line 32, in <module>
    run(config)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\main.py", line 19, in run
    scenario.run()
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\base\scenario.py", line 85, in run
    self.ready()
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\base\scenario.py", line 73, in ready
    self.solver.learn(self.env, num_epochs=self.config.num_train_epochs)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\rl_solver.py", line 201, in learn
    solution = self.learn_with_instance(instance, revenue2cost_list, epoch_logprobs)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\rl_solver.py", line 148, in learn_with_instance
    sub_env = self.SubEnv(p_net, v_net, self.controller, self.recorder, self.counter, **self.basic_config)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\hrl_ra\sub_env.py", line 11, in __init__
    super(SubEnv, self).__init__(p_net, v_net, controller, recorder, counter, **kwargs)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\sub_rl_environment.py", line 127, in __init__
    super(JointPRStepSubRLEnv, self).__init__(p_net, v_net, controller, recorder, counter, **kwargs)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\sub_rl_environment.py", line 19, in __init__
    super(SubRLEnv, self).__init__(**kwargs)
  File "C:\Users\123\Desktop\hrl-acra-main\hrl-acra-main\solver\learning\rl_environment.py", line 26, in __init__
    self.link_sum_attr_benchmarks = self.p_net.link_sum_attr_benchmarks
AttributeError: 'PhysicalNetwork' object has no attribute 'link_sum_attr_benchmarks'
May I ask why this problem is encountered

**Comment by GeminiLight** [comment]
Hi, the results of my running testing show that the AC rate is not always 1. Could you provide me with more details on any modifications to the original code?

**Comment by MerrillLi** [comment]
I may know what happens... if you set the decoding strategy to "beam," the AC will have a very high probability of being 1...
Set to greedy can reproduce the results reported in the paper.

**Comment by GeminiLight** [comment]
Thanks for your feedback. I will check this issue this week.
